"""Added matches and user actions

Revision ID: 3179ab344ca3
Revises: 8c37f9ab3616
Create Date: 2025-12-27 20:17:10.123148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3179ab344ca3'
down_revision = '8c37f9ab3616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_a_id', sa.Integer(), nullable=False),
    sa.Column('user_b_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('user_a_id < user_b_id', name='ck_match_user_order'),
    sa.ForeignKeyConstraint(['user_a_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a_id', 'user_b_id', name='uq_match_user_a_user_b')
    )
    op.create_table('user_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('LIKE', 'PASS', name='action_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('actor_id != target_id', name='ck_useraction_no_self_action'),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'target_id', name='uq_useraction_actor_target')
    )
    with op.batch_alter_table('user_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_action_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_action_target_id'), ['target_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_action_target_id'))
        batch_op.drop_index(batch_op.f('ix_user_action_actor_id'))

    op.drop_table('user_action')
    op.drop_table('match')
    # ### end Alembic commands ###
