"""Added category to hobbies

Revision ID: 814463ff81df
Revises: 3179ab344ca3
Create Date: 2026-01-03 20:30:47.771800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814463ff81df'
down_revision = '3179ab344ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
